# Generated by Django 5.0.3 on 2026-03-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CEFRLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('name_vi', models.CharField(max_length=50)),
                ('order', models.SmallIntegerField(db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'curriculum_cefrlevel',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.SmallIntegerField(db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('passing_score', models.SmallIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'curriculum_chapter',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('order', models.SmallIntegerField(db_index=True)),
                ('is_premium', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'curriculum_course',
                'ordering': ['level__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.SmallIntegerField(db_index=True)),
                ('lesson_type', models.CharField(choices=[('listening', 'Nghe'), ('speaking', 'Nói'), ('reading', 'Đọc'), ('writing', 'Viết'), ('vocabulary', 'Từ vựng'), ('pronunciation', 'Phát âm'), ('assessment', 'Kiểm tra')], db_index=True, max_length=15)),
                ('estimated_minutes', models.SmallIntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'curriculum_lesson',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('listening', 'Listening'), ('speaking', 'Speaking'), ('reading', 'Reading'), ('writing', 'Writing')], max_length=15)),
                ('exercise_id', models.BigIntegerField()),
                ('order', models.SmallIntegerField(default=1)),
                ('passing_score', models.SmallIntegerField(default=60)),
            ],
            options={
                'db_table': 'curriculum_lessonexercise',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UnlockRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.SmallIntegerField(default=60)),
            ],
            options={
                'db_table': 'curriculum_unlockrule',
            },
        ),
    ]
