# Generated by Django 5.0.3 on 2026-03-24 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='curriculum.cefrlevel'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='curriculum.course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.chapter'),
        ),
        migrations.AddField(
            model_name='lessonexercise',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='curriculum.lesson'),
        ),
        migrations.AddField(
            model_name='unlockrule',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_rules', to='curriculum.lesson'),
        ),
        migrations.AddField(
            model_name='unlockrule',
            name='required_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='curriculum.lesson'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['level', 'order'], name='curriculum__level_i_3c6b4c_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['course', 'order'], name='curriculum__course__fa5458_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['chapter', 'order'], name='curriculum__chapter_f2c8e8_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['lesson_type'], name='curriculum__lesson__8861d6_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonexercise',
            index=models.Index(fields=['exercise_type', 'exercise_id'], name='curriculum__exercis_090e8e_idx'),
        ),
    ]
