# Generated by Django 5.0.3 on 2026-03-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('listening', 'Nghe'), ('speaking', 'Nói'), ('reading', 'Đọc'), ('writing', 'Viết'), ('grammar', 'Ngữ pháp'), ('vocabulary', 'Từ vựng'), ('pronunciation', 'Phát âm'), ('assessment', 'Kiểm tra')], db_index=True, max_length=15),
        ),
    ]
