# Generated by Django 5.0.3 on 2026-03-31 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_grammar_lesson_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('audio', 'Audio'), ('pdf', 'PDF'), ('image', 'Image'), ('video', 'Video'), ('other', 'Other')], default='other', max_length=10)),
                ('s3_key', models.CharField(blank=True, default='', max_length=500)),
                ('original_name', models.CharField(max_length=255)),
                ('file_size_bytes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to='curriculum.lesson')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_source_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'curriculum_sourcefile',
                'ordering': ['-created_at'],
            },
        ),
    ]
