# Generated by Django 5.0.3 on 2026-04-01 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_sourcefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_passage', models.TextField(blank=True, default='', help_text='HTML/Markdown reading passage for the lesson.')),
                ('reading_image_url', models.CharField(blank=True, default='', help_text='Optional hero image for the reading passage.', max_length=500)),
                ('reading_questions', models.JSONField(blank=True, default=list, help_text='[{"question":"…","options":["a","b","c","d"],"correct":0,"explanation":"…"}]')),
                ('vocab_items', models.JSONField(blank=True, default=list, help_text='[{"word":"headache","pos":"noun","ipa":"/ˈhed.eɪk/","meaning_vi":"đau đầu","definition_en":"A pain inside your head.","example_en":"I have a headache.","example_vi":"Tôi bị đau đầu.","collocations":["have a ~","splitting ~"],"highlight_in_passage":true}]')),
                ('vocab_word_ids', models.JSONField(blank=True, default=list, help_text='List of vocabulary.Word PKs linked to this lesson (for SRS tracking).')),
                ('grammar_topic_id', models.IntegerField(blank=True, help_text='FK to grammar.GrammarTopic (for deep-link).', null=True)),
                ('grammar_title', models.CharField(blank=True, default='', max_length=200)),
                ('grammar_note', models.TextField(blank=True, default='', help_text='Short grammar explanation in context of the lesson theme.')),
                ('grammar_examples', models.JSONField(blank=True, default=list, help_text='[{"en":"She is tall.","vi":"Cô ấy cao.","highlight":"is"}]')),
                ('exercises', models.JSONField(blank=True, default=list, help_text='[{"type":"gap-fill|mc|rewrite|error|cloze","prompt":"…","options":["a","b"],"correct":0,"explanation":"…"}]')),
                ('srs_review_count', models.SmallIntegerField(default=5, help_text='Number of SRS review items to pull from previous chapters.')),
                ('completion_xp', models.SmallIntegerField(default=10)),
                ('bonus_xp', models.SmallIntegerField(default=50, help_text='Extra XP if score >= 80%.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='curriculum.lesson')),
            ],
            options={
                'db_table': 'curriculum_lessoncontent',
            },
        ),
    ]
