# Generated by Django 5.0.3 on 2026-04-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_add_lesson_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='grammar_sections',
            field=models.JSONField(blank=True, default=list, help_text='[{"title":"...","grammar_topic_id":null,"note":"...","examples":[...],"exercises":[{"type":"gap-fill","prompt":"...","options":[...],"correct":0,"explanation":"..."}]}]'),
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='skill_sections',
            field=models.JSONField(blank=True, default=dict, help_text='{"dictation":[...],"shadowing":[...],"guided_writing":[...]}'),
        ),
    ]
