# Generated by Django 5.0.3 on 2026-04-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_port_grammar_skill_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='listening_content',
            field=models.JSONField(blank=True, default=dict, help_text='{"audio_text":"...","translation_vi":"...","sentences":[{"text":"...","translation_vi":"...","audio_url":""}],"speed":0.9,"comprehension_questions":[{"question":"...","options":[...],"correct":0,"explanation":"..."}],"dictation_sentences":[{"text":"...","hint":"...","translation_vi":"..."}]}'),
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='speaking_content',
            field=models.JSONField(blank=True, default=dict, help_text='{"mode":"repeat|shadow|dialogue","sentences":[{"text":"...","translation_vi":"...","speed":0.85,"focus_words":["key","words"]}],"dialogue":[{"speaker":"A","text":"...","translation_vi":"..."}]}'),
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='writing_content',
            field=models.JSONField(blank=True, default=dict, help_text='{"exercises":[{"type":"word_order|gap_fill|sentence_completion|guided|free","prompt":"...","prompt_vi":"...","grammar_hint":"...","items":[["word","order","items"]],"correct_answer":"...","min_words":8,"max_words":25,"sample_answer":"..."}]}'),
        ),
    ]
