# Generated by Django 5.0.3 on 2026-04-05 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticePassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('full_text', models.TextField(help_text='Full passage content in English')),
                ('translation_vi', models.TextField(blank=True, help_text='Vietnamese translation of the full passage', null=True)),
                ('sentences_json', models.JSONField(default=list, help_text='List of sentences with individual TTS audio URLs')),
                ('full_audio_url', models.CharField(blank=True, help_text='TTS audio for the complete passage', max_length=500, null=True)),
                ('topic', models.CharField(db_index=True, help_text="e.g. 'Health - Symptoms & Illnesses'", max_length=200)),
                ('topic_slug', models.SlugField(help_text='URL-safe slug derived from topic', max_length=220)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], db_index=True, max_length=3)),
                ('difficulty_tag', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('word_count', models.SmallIntegerField(default=0)),
                ('vocab_highlights_json', models.JSONField(blank=True, help_text='[{word, ipa, meaning_vi, part_of_speech}]', null=True)),
                ('grammar_notes', models.TextField(blank=True, help_text='Key grammar patterns used in this passage', null=True)),
                ('tts_voice', models.CharField(default='en-US-AriaNeural', help_text='Edge-TTS voice name for generating audio', max_length=50)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Practice Passage',
                'verbose_name_plural': 'Practice Passages',
                'db_table': 'skill_practice_passage',
                'ordering': ['cefr_level', 'topic', 'difficulty_tag'],
                'indexes': [models.Index(fields=['cefr_level', 'topic'], name='skill_pract_cefr_le_f7a326_idx'), models.Index(fields=['cefr_level', 'is_published'], name='skill_pract_cefr_le_dc5f71_idx'), models.Index(fields=['topic_slug'], name='skill_pract_topic_s_0d9685_idx')],
            },
        ),
        migrations.CreateModel(
            name='DictationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_index', models.SmallIntegerField(blank=True, help_text='null means full-passage mode', null=True)),
                ('user_input', models.TextField()),
                ('accuracy_percent', models.SmallIntegerField(default=0)),
                ('diff_json', models.JSONField(default=list, help_text='[{word, match, correct_word}] word-level diff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictation_attempts', to=settings.AUTH_USER_MODEL)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictation_attempts', to='skill_practice.practicepassage')),
            ],
            options={
                'verbose_name': 'Dictation Attempt',
                'verbose_name_plural': 'Dictation Attempts',
                'db_table': 'skill_practice_dictation_attempt',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'passage'], name='skill_pract_user_id_6e1315_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPassageProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('dictation', 'Chính tả'), ('shadowing', 'Shadowing')], max_length=15)),
                ('status', models.CharField(choices=[('not_started', 'Chưa bắt đầu'), ('in_progress', 'Đang học'), ('completed', 'Hoàn thành')], default='not_started', max_length=15)),
                ('best_score', models.SmallIntegerField(default=0, help_text='Dictation: word accuracy %. Shadowing: avg self-assessment (1-5 scaled to 0-100)')),
                ('attempts', models.SmallIntegerField(default=0)),
                ('sentences_completed_json', models.JSONField(default=dict, help_text='{"0": true, "1": false} — per-sentence completion')),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='skill_practice.practicepassage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passage_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Passage Progress',
                'verbose_name_plural': 'User Passage Progresses',
                'db_table': 'skill_practice_user_progress',
                'indexes': [models.Index(fields=['user', 'mode'], name='skill_pract_user_id_07232c_idx'), models.Index(fields=['user', 'passage'], name='skill_pract_user_id_750134_idx')],
                'unique_together': {('user', 'passage', 'mode')},
            },
        ),
    ]
