# Generated by Django 5.0.3 on 2026-03-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('streak_reminder', 'Nhắc nhở streak'), ('flashcard_due', 'Ôn flashcard đến hạn'), ('grading_done', 'Chấm bài xong'), ('new_lesson', 'Bài học mới'), ('achievement', 'Nhận huy hiệu'), ('daily_challenge', 'Daily Challenge mới'), ('payment_success', 'Thanh toán thành công'), ('payment_failed', 'Thanh toán thất bại'), ('subscription_expiring', 'Gói chuẩn bị hết hạn'), ('system', 'Thông báo hệ thống')], db_index=True, max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('reference_id', models.BigIntegerField(blank=True, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=30, null=True)),
                ('action_url', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('streak_reminder', 'Nhắc nhở streak'), ('flashcard_due', 'Ôn flashcard đến hạn'), ('grading_done', 'Chấm bài xong'), ('new_lesson', 'Bài học mới'), ('achievement', 'Nhận huy hiệu'), ('daily_challenge', 'Daily Challenge mới'), ('payment_success', 'Thanh toán thành công'), ('payment_failed', 'Thanh toán thất bại'), ('subscription_expiring', 'Gói chuẩn bị hết hạn'), ('system', 'Thông báo hệ thống')], max_length=25, unique=True)),
                ('title_vi', models.CharField(max_length=200)),
                ('message_template_vi', models.TextField(help_text='Sử dụng {{var}} cho biến động')),
                ('push_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notifications_template',
            },
        ),
    ]
