# Generated by Django 5.0.3 on 2026-03-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='flashcard_notify_hour',
            field=models.SmallIntegerField(default=8, help_text='Giờ nhắc nhở flashcard (0-23, múi giờ ICT UTC+7)'),
        ),
    ]
