# Generated by Django 5.0.3 on 2026-03-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_flashcard_notify_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False, help_text='Cờ bật tắt bảo mật 2 lớp 2FA'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='Bí mật TOTP base32', max_length=32, null=True),
        ),
    ]
