# Generated by Django 5.0.3 on 2026-03-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usersettings_is_2fa_enabled_usersettings_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Giáo viên'), ('student', 'Học viên'), ('support', 'Nhân viên hỗ trợ')], db_index=True, default='student', max_length=10),
        ),
    ]
