# Generated by Django 5.0.3 on 2026-03-24 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('cefr_level', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], max_length=3, null=True)),
                ('domain', models.CharField(blank=True, max_length=30, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, help_text='null = system deck', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vocabulary_flashcarddeck',
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_text', models.CharField(max_length=300)),
                ('back_text', models.TextField()),
                ('card_type', models.CharField(choices=[('word_to_def', 'Từ → Định nghĩa'), ('def_to_word', 'Định nghĩa → Từ'), ('audio_to_word', 'Âm thanh → Từ')], default='word_to_def', max_length=20)),
                ('order', models.SmallIntegerField(default=1)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='vocabulary.flashcarddeck')),
            ],
            options={
                'db_table': 'vocabulary_flashcard',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserFlashcardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval_days', models.SmallIntegerField(default=1)),
                ('repetitions', models.SmallIntegerField(default=0)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('last_rating', models.SmallIntegerField(blank=True, null=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_mastered', models.BooleanField(default=False)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.flashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vocabulary_userflashcardprogress',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=100)),
                ('part_of_speech', models.CharField(blank=True, choices=[('noun', 'Danh từ'), ('verb', 'Động từ'), ('adjective', 'Tính từ'), ('adverb', 'Trạng từ'), ('phrase', 'Cụm từ'), ('other', 'Khác')], max_length=20, null=True)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], db_index=True, max_length=3)),
                ('domain', models.CharField(blank=True, db_index=True, help_text='business/casual/medical/academic/travel', max_length=30, null=True)),
                ('ipa_uk', models.CharField(blank=True, max_length=100, null=True)),
                ('ipa_us', models.CharField(blank=True, max_length=100, null=True)),
                ('audio_uk_s3_key', models.CharField(blank=True, max_length=500, null=True)),
                ('audio_us_s3_key', models.CharField(blank=True, max_length=500, null=True)),
                ('meaning_vi', models.TextField()),
                ('definition_en', models.TextField(blank=True, null=True)),
                ('example_en', models.TextField(blank=True, null=True)),
                ('example_vi', models.TextField(blank=True, null=True)),
                ('collocations_json', models.JSONField(blank=True, null=True)),
                ('synonyms_json', models.JSONField(blank=True, null=True)),
                ('antonyms_json', models.JSONField(blank=True, null=True)),
                ('mnemonic', models.TextField(blank=True, null=True)),
                ('frequency_rank', models.IntegerField(blank=True, null=True)),
                ('register', models.CharField(blank=True, choices=[('formal', 'Trang trọng'), ('informal', 'Thân mật'), ('slang', 'Tiếng lóng'), ('academic', 'Học thuật')], max_length=15, null=True)),
                ('image_key', models.CharField(blank=True, max_length=500, null=True)),
                ('is_oxford_3000', models.BooleanField(db_index=True, default=False)),
                ('is_oxford_5000', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vocabulary_word',
                'indexes': [models.Index(fields=['word'], name='vocabulary__word_7965e8_idx'), models.Index(fields=['cefr_level', 'domain'], name='vocabulary__cefr_le_bc5e49_idx')],
            },
        ),
        migrations.AddField(
            model_name='flashcard',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vocabulary.word'),
        ),
        migrations.AddConstraint(
            model_name='userflashcardprogress',
            constraint=models.UniqueConstraint(fields=('user', 'flashcard'), name='unique_user_card'),
        ),
    ]
