# Generated by Django 5.0.3 on 2026-03-26 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='domain',
            field=models.CharField(blank=True, db_index=True, help_text='general|everyday|business|technology|academic|medical|health|travel|food|vegetables|animals|nature|art', max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_cards', models.SmallIntegerField(default=0)),
                ('review_cards', models.SmallIntegerField(default=0)),
                ('total_reviewed', models.SmallIntegerField(default=0)),
                ('correct_count', models.SmallIntegerField(default=0)),
                ('accuracy_pct', models.FloatField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='vocabulary.flashcarddeck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vocabulary_studysession',
                'indexes': [models.Index(fields=['user', 'deck', 'started_at'], name='vocabulary__user_id_5b5219_idx')],
            },
        ),
    ]
