# Generated by Django 5.0.3 on 2026-03-28 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manage_users', models.BooleanField(default=False)),
                ('manage_content', models.BooleanField(default=False)),
                ('manage_payments', models.BooleanField(default=False)),
                ('manage_assessments', models.BooleanField(default=False)),
                ('manage_notifications', models.BooleanField(default=False)),
                ('manage_gamification', models.BooleanField(default=False)),
                ('view_analytics', models.BooleanField(default=False)),
                ('manage_settings', models.BooleanField(default=False)),
                ('view_audit_log', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_portal_staffpermission',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField()),
                ('value_type', models.CharField(choices=[('str', 'Text'), ('int', 'Số nguyên'), ('bool', 'Boolean'), ('json', 'JSON')], default='str', max_length=5)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('general', 'Chung'), ('payment', 'Thanh toán'), ('ai_grading', 'AI Chấm bài'), ('email', 'Email'), ('security', 'Bảo mật'), ('gamification', 'Gamification')], db_index=True, default='general', max_length=20)),
                ('is_editable', models.BooleanField(default=True, help_text='False = hiển thị để biết, không cho sửa')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_portal_systemsetting',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xoá'), ('ban', 'Khoá tài khoản'), ('unban', 'Mở khoá tài khoản'), ('bulk_notify', 'Gửi thông báo hàng loạt'), ('extend_sub', 'Gia hạn gói'), ('grant_xp', 'Cấp XP thủ công'), ('retry_job', 'Thử lại AI Job'), ('other', 'Khác')], db_index=True, max_length=20)),
                ('model_name', models.CharField(db_index=True, max_length=50)),
                ('object_id', models.BigIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('changes_json', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_portal_auditlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_user', 'created_at'], name='admin_porta_admin_u_1c2eac_idx'), models.Index(fields=['action', 'model_name'], name='admin_porta_action_e917ca_idx')],
            },
        ),
    ]
