# Generated by Django 5.0.3 on 2026-03-24 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.SmallIntegerField(default=0)),
                ('longest_streak', models.SmallIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('streak_protected_until', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'progress_dailystreak',
            },
        ),
        migrations.CreateModel(
            name='ExerciseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('listening', 'Listening'), ('speaking', 'Speaking'), ('reading', 'Reading'), ('writing', 'Writing')], db_index=True, max_length=15)),
                ('exercise_id', models.BigIntegerField(db_index=True)),
                ('score', models.SmallIntegerField()),
                ('passed', models.BooleanField()),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('detail_json', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'progress_exerciseresult',
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Khoá'), ('available', 'Sẵn sàng'), ('in_progress', 'Đang học'), ('completed', 'Hoàn thành')], db_index=True, default='locked', max_length=15)),
                ('best_score', models.SmallIntegerField(blank=True, null=True)),
                ('attempts_count', models.SmallIntegerField(default=0)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'progress_lessonprogress',
            },
        ),
        migrations.CreateModel(
            name='SpeakingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.BigIntegerField(db_index=True)),
                ('audio_s3_key', models.CharField(max_length=500)),
                ('audio_duration_seconds', models.FloatField(blank=True, null=True)),
                ('audio_size_bytes', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang chấm'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại')], db_index=True, default='pending', max_length=15)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('target_sentence', models.CharField(blank=True, max_length=500, null=True)),
                ('ai_score', models.SmallIntegerField(blank=True, null=True)),
                ('score_pronunciation', models.SmallIntegerField(blank=True, null=True)),
                ('score_fluency', models.SmallIntegerField(blank=True, null=True)),
                ('score_intonation', models.SmallIntegerField(blank=True, null=True)),
                ('score_vocabulary', models.SmallIntegerField(blank=True, null=True)),
                ('feedback_vi', models.TextField(blank=True, null=True)),
                ('error_list_json', models.JSONField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'progress_speakingsubmission',
            },
        ),
        migrations.CreateModel(
            name='UserEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Đang học'), ('paused', 'Tạm dừng'), ('completed', 'Hoàn thành'), ('dropped', 'Bỏ dở')], db_index=True, default='active', max_length=15)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'progress_userenrollment',
            },
        ),
        migrations.CreateModel(
            name='WritingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.BigIntegerField(db_index=True)),
                ('content_text', models.TextField()),
                ('word_count', models.SmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang chấm'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại')], db_index=True, default='pending', max_length=15)),
                ('ai_score', models.SmallIntegerField(blank=True, null=True)),
                ('score_task_achievement', models.SmallIntegerField(blank=True, null=True)),
                ('score_grammar', models.SmallIntegerField(blank=True, null=True)),
                ('score_vocabulary', models.SmallIntegerField(blank=True, null=True)),
                ('score_coherence', models.SmallIntegerField(blank=True, null=True)),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('error_list_json', models.JSONField(blank=True, null=True)),
                ('vocab_cefr_json', models.JSONField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('teacher_comment', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'progress_writingsubmission',
            },
        ),
        migrations.CreateModel(
            name='AIGradingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('speaking', 'Speaking'), ('writing', 'Writing')], db_index=True, max_length=15)),
                ('submission_id', models.BigIntegerField(db_index=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Xếp hàng'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại'), ('retrying', 'Thử lại')], db_index=True, default='queued', max_length=15)),
                ('retry_count', models.SmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ai_model_used', models.CharField(blank=True, max_length=50, null=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'progress_aigradingjob',
                'indexes': [models.Index(fields=['status'], name='progress_ai_status_4235eb_idx'), models.Index(fields=['job_type', 'status'], name='progress_ai_job_typ_cac6fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='CumulativeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listening_avg', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('speaking_avg', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('reading_avg', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('writing_avg', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_avg', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_exercises_done', models.IntegerField(default=0)),
                ('cefr_equivalent', models.CharField(blank=True, max_length=3, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.cefrlevel')),
            ],
            options={
                'db_table': 'progress_cumulativescore',
            },
        ),
    ]
