# Generated by Django 5.0.3 on 2026-03-24 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0002_initial'),
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cumulativescore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailystreak',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exerciseresult',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.lesson'),
        ),
        migrations.AddField(
            model_name='exerciseresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.lesson'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speakingsubmission',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.lesson'),
        ),
        migrations.AddField(
            model_name='speakingsubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='curriculum.course'),
        ),
        migrations.AddField(
            model_name='userenrollment',
            name='current_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.lesson'),
        ),
        migrations.AddField(
            model_name='userenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writingsubmission',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.lesson'),
        ),
        migrations.AddField(
            model_name='writingsubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='cumulativescore',
            constraint=models.UniqueConstraint(fields=('user', 'level'), name='unique_user_level_score'),
        ),
        migrations.AddIndex(
            model_name='exerciseresult',
            index=models.Index(fields=['user', 'exercise_type', 'exercise_id'], name='progress_ex_user_id_028cfc_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseresult',
            index=models.Index(fields=['user', 'created_at'], name='progress_ex_user_id_1113a2_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['user', 'status'], name='progress_le_user_id_2913b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.UniqueConstraint(fields=('user', 'lesson'), name='unique_lesson_progress'),
        ),
        migrations.AddIndex(
            model_name='speakingsubmission',
            index=models.Index(fields=['user', 'status'], name='progress_sp_user_id_9037e2_idx'),
        ),
        migrations.AddIndex(
            model_name='speakingsubmission',
            index=models.Index(fields=['user', 'exercise_id'], name='progress_sp_user_id_761b32_idx'),
        ),
        migrations.AddIndex(
            model_name='userenrollment',
            index=models.Index(fields=['user', 'status'], name='progress_us_user_id_999ef8_idx'),
        ),
        migrations.AddIndex(
            model_name='userenrollment',
            index=models.Index(fields=['course', 'status'], name='progress_us_course__569d09_idx'),
        ),
        migrations.AddConstraint(
            model_name='userenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('user', 'course'), name='unique_active_enrollment'),
        ),
        migrations.AddIndex(
            model_name='writingsubmission',
            index=models.Index(fields=['user', 'status'], name='progress_wr_user_id_c45cae_idx'),
        ),
        migrations.AddIndex(
            model_name='writingsubmission',
            index=models.Index(fields=['user', 'exercise_id'], name='progress_wr_user_id_207fc2_idx'),
        ),
    ]
