# Generated by Django 5.0.3 on 2026-03-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseresult',
            name='exercise_type',
            field=models.CharField(choices=[('listening', 'Listening'), ('speaking', 'Speaking'), ('reading', 'Reading'), ('writing', 'Writing'), ('grammar', 'Grammar')], db_index=True, max_length=15),
        ),
    ]
