# Generated by Django 5.0.3 on 2026-03-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_add_grammar_exercise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseresult',
            name='exercise_type',
            field=models.CharField(choices=[('listening', 'Listening'), ('speaking', 'Speaking'), ('reading', 'Reading'), ('writing', 'Writing'), ('grammar', 'Grammar'), ('exam', 'Exam')], db_index=True, max_length=15),
        ),
    ]
