# Generated by Django 5.0.3 on 2026-03-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('skill', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('mixed', 'Mixed')], max_length=10)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], db_index=True, max_length=3)),
                ('time_limit_minutes', models.SmallIntegerField()),
                ('passing_score', models.SmallIntegerField(default=60)),
                ('total_questions', models.SmallIntegerField()),
                ('structure_json', models.JSONField(default=dict, help_text='{"mc": 10, "gap_fill": 5, "drag_drop": 5}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exercises_examset',
            },
        ),
        migrations.CreateModel(
            name='ListeningExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio_file', models.CharField(help_text='S3 key của file MP3', max_length=500)),
                ('audio_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('context_hint', models.TextField(blank=True, null=True)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], db_index=True, max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exercises_listeningexercise',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading')], db_index=True, max_length=15)),
                ('exercise_id', models.BigIntegerField(db_index=True)),
                ('question_type', models.CharField(choices=[('mc', 'Multiple Choice'), ('gap_fill', 'Gap Fill'), ('drag_drop', 'Drag & Drop')], max_length=15)),
                ('question_text', models.TextField()),
                ('order', models.SmallIntegerField(default=1)),
                ('correct_answers_json', models.JSONField(help_text='["A", "B"] — supports multiple correct answers')),
                ('explanation', models.TextField(blank=True, null=True)),
                ('points', models.SmallIntegerField(default=1)),
                ('is_locked_initially', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'exercises_question',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=500)),
                ('order', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'exercises_questionoption',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReadingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('article_text', models.TextField(help_text='Nội dung bài đọc (HTML/Markdown)')),
                ('vocab_tooltip_json', models.JSONField(default=list, help_text='[{"word": "...", "ipa": "...", "meaning_vi": "..."}]')),
                ('cefr_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], db_index=True, max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exercises_readingexercise',
            },
        ),
        migrations.CreateModel(
            name='SpeakingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('scenario', models.TextField(help_text='Mô tả tình huống nhập vai')),
                ('dialogue_json', models.JSONField(default=list, help_text='[{"role": "AI", "text": "...", "audio_key": "..."}]')),
                ('target_sentence', models.TextField(help_text='Câu học viên cần nói')),
                ('target_audio_key', models.CharField(help_text='S3 key audio mẫu', max_length=500)),
                ('karaoke_words_json', models.JSONField(default=list, help_text='[{"word": "hello", "start_ms": 0, "end_ms": 400}]')),
                ('cefr_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], db_index=True, max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exercises_speakingexercise',
            },
        ),
        migrations.CreateModel(
            name='WritingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('prompt_text', models.TextField(help_text='Đề bài')),
                ('prompt_description', models.TextField(help_text='Hướng dẫn chi tiết')),
                ('min_words', models.SmallIntegerField(default=150)),
                ('max_words', models.SmallIntegerField(default=300)),
                ('time_limit_minutes', models.SmallIntegerField(default=30)),
                ('structure_tips_json', models.JSONField(default=list, help_text='["Paragraph 1: Introduction...", "Paragraph 2: ..."]')),
                ('cefr_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], db_index=True, max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exercises_writingexercise',
            },
        ),
    ]
