# Generated by Django 5.0.3 on 2026-03-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='exercise_type',
            field=models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('grammar', 'Grammar')], db_index=True, max_length=15),
        ),
    ]
