# Generated by Django 5.0.3 on 2026-03-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_grammar_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningexercise',
            name='max_plays',
            field=models.SmallIntegerField(default=0, help_text='0 = unlimited'),
        ),
        migrations.AddField(
            model_name='listeningexercise',
            name='time_limit_seconds',
            field=models.SmallIntegerField(default=0, help_text='0 = no limit'),
        ),
    ]
