# Generated by Django 5.0.3 on 2026-03-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_add_max_plays_time_limit_to_listening'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='passage_ref_end',
            field=models.IntegerField(blank=True, help_text='Char offset end in passage', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='passage_ref_start',
            field=models.IntegerField(blank=True, help_text='Char offset start in passage', null=True),
        ),
        migrations.AddField(
            model_name='readingexercise',
            name='time_limit_seconds',
            field=models.SmallIntegerField(default=0, help_text='0 = no limit'),
        ),
    ]
