# Generated by Django 5.0.3 on 2026-03-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_add_reading_time_limit_and_passage_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingexercise',
            name='time_limit_seconds',
            field=models.SmallIntegerField(default=60, help_text='Max recording seconds'),
        ),
    ]
