# Generated by Django 5.0.3 on 2026-03-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_add_speaking_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='examset',
            name='exam_type',
            field=models.CharField(choices=[('progress_check', 'Progress Check'), ('mock_test', 'Mock Test'), ('placement', 'Placement Test')], db_index=True, default='mock_test', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='exercise_type',
            field=models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('grammar', 'Grammar'), ('exam', 'Exam')], db_index=True, max_length=15),
        ),
    ]
