# Generated by Django 5.0.3 on 2026-03-31 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0004_sourcefile'),
        ('exercises', '0007_examset_exam_type_alter_question_exercise_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('due_date', models.DateTimeField()),
                ('assign_to_all', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='curriculum.course')),
                ('exam_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='exercises.examset')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_classassignment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='teacher.classassignment')),
            ],
            options={
                'db_table': 'teacher_assignmentstudent',
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
