# Generated by Django 5.0.3 on 2026-05-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIGradingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.BigIntegerField(db_index=True)),
                ('submission_type', models.CharField(max_length=20)),
                ('prompt_hash', models.CharField(max_length=64)),
                ('response_raw', models.TextField()),
                ('score', models.SmallIntegerField(null=True)),
                ('latency_ms', models.IntegerField()),
                ('status', models.CharField(default='success', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_grading_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
