"""
Management command: seed_minimal_pairs
Populates MinimalPairSet + MinimalPair with 30+ commonly-confused pairs for
Vietnamese learners of English.

Usage:
    python manage.py seed_minimal_pairs          # skip existing, add new
    python manage.py seed_minimal_pairs --clear  # delete all & re-seed
"""

from django.core.management.base import BaseCommand

from apps.pronunciation.models import MinimalPair, MinimalPairSet

# ── Data ──────────────────────────────────────────────────────────────────────
# Format:  title, phoneme_1, phoneme_2, description, cefr_level,
#          pairs: list of [ {word, ipa, meaning} alternating p1/p2/p1/p2... ]

MINIMAL_PAIRS_DATA = [
    # ── GROUP 1: Short vs Long Vowels ──────────────────────────────────────
    {
        "title": "/ɪ/ vs /iː/ — ship / sheep",
        "focus_phoneme_1": "/ɪ/",
        "focus_phoneme_2": "/iː/",
        "description": "Phân biệt nguyên âm ngắn /ɪ/ (ship) và dài /iː/ (sheep). Người Việt thường phát âm cả hai giống nhau.",
        "cefr_level": "A1",
        "order": 1,
        "pairs": [
            {"word": "ship",  "ipa": "/ʃɪp/",   "meaning": "con tàu"},
            {"word": "sheep", "ipa": "/ʃiːp/",  "meaning": "con cừu"},
            {"word": "bit",   "ipa": "/bɪt/",   "meaning": "một chút"},
            {"word": "beat",  "ipa": "/biːt/",  "meaning": "đánh nhịp"},
            {"word": "fill",  "ipa": "/fɪl/",   "meaning": "lấp đầy"},
            {"word": "feel",  "ipa": "/fiːl/",  "meaning": "cảm thấy"},
            {"word": "sit",   "ipa": "/sɪt/",   "meaning": "ngồi"},
            {"word": "seat",  "ipa": "/siːt/",  "meaning": "chỗ ngồi"},
            {"word": "live",  "ipa": "/lɪv/",   "meaning": "sống"},
            {"word": "leave", "ipa": "/liːv/",  "meaning": "rời đi"},
        ],
    },
    {
        "title": "/æ/ vs /e/ — bad / bed",
        "focus_phoneme_1": "/æ/",
        "focus_phoneme_2": "/e/",
        "description": "Phân biệt /æ/ (miệng mở rộng) và /e/ (miệng hé). Rất dễ nhầm lẫn với người Việt.",
        "cefr_level": "A1",
        "order": 2,
        "pairs": [
            {"word": "bad",  "ipa": "/bæd/",  "meaning": "xấu"},
            {"word": "bed",  "ipa": "/bed/",  "meaning": "giường"},
            {"word": "man",  "ipa": "/mæn/",  "meaning": "người đàn ông"},
            {"word": "men",  "ipa": "/men/",  "meaning": "đàn ông (số nhiều)"},
            {"word": "hat",  "ipa": "/hæt/",  "meaning": "cái mũ"},
            {"word": "het",  "ipa": "/het/",  "meaning": "rào cản (từ cổ)"},
            {"word": "sand", "ipa": "/sænd/", "meaning": "cát"},
            {"word": "send", "ipa": "/send/", "meaning": "gửi"},
            {"word": "band", "ipa": "/bænd/", "meaning": "ban nhạc"},
            {"word": "bend", "ipa": "/bend/", "meaning": "uốn cong"},
        ],
    },
    {
        "title": "/ʌ/ vs /æ/ — cup / cap",
        "focus_phoneme_1": "/ʌ/",
        "focus_phoneme_2": "/æ/",
        "description": "Phân biệt /ʌ/ (giữa miệng, hơi mở) và /æ/ (miệng mở rộng, hơi tiến ra trước).",
        "cefr_level": "A1",
        "order": 3,
        "pairs": [
            {"word": "cup",  "ipa": "/kʌp/",  "meaning": "cái ly"},
            {"word": "cap",  "ipa": "/kæp/",  "meaning": "mũ lưỡi trai"},
            {"word": "luck", "ipa": "/lʌk/",  "meaning": "may mắn"},
            {"word": "lack", "ipa": "/læk/",  "meaning": "thiếu"},
            {"word": "cut",  "ipa": "/kʌt/",  "meaning": "cắt"},
            {"word": "cat",  "ipa": "/kæt/",  "meaning": "con mèo"},
            {"word": "bun",  "ipa": "/bʌn/",  "meaning": "bánh mì tròn"},
            {"word": "ban",  "ipa": "/bæn/",  "meaning": "cấm"},
            {"word": "mud",  "ipa": "/mʌd/",  "meaning": "bùn"},
            {"word": "mad",  "ipa": "/mæd/",  "meaning": "điên"},
        ],
    },
    {
        "title": "/uː/ vs /ʊ/ — fool / full",
        "focus_phoneme_1": "/uː/",
        "focus_phoneme_2": "/ʊ/",
        "description": "Phân biệt /uː/ (nguyên âm dài, môi trề ra) và /ʊ/ (nguyên âm ngắn, lỏng hơn).",
        "cefr_level": "A2",
        "order": 4,
        "pairs": [
            {"word": "fool", "ipa": "/fuːl/",  "meaning": "kẻ ngốc"},
            {"word": "full", "ipa": "/fʊl/",   "meaning": "đầy"},
            {"word": "pool", "ipa": "/puːl/",  "meaning": "hồ bơi"},
            {"word": "pull", "ipa": "/pʊl/",   "meaning": "kéo"},
            {"word": "Luke", "ipa": "/luːk/",  "meaning": "tên người (Luke)"},
            {"word": "look", "ipa": "/lʊk/",   "meaning": "nhìn"},
            {"word": "food", "ipa": "/fuːd/",  "meaning": "thức ăn"},
            {"word": "foot", "ipa": "/fʊt/",   "meaning": "bàn chân"},
            {"word": "who'd","ipa": "/huːd/",  "meaning": "người nào đó"},
            {"word": "hood", "ipa": "/hʊd/",   "meaning": "mũ trùm đầu"},
        ],
    },
    {
        "title": "/e/ vs /eɪ/ — bed / bade",
        "focus_phoneme_1": "/e/",
        "focus_phoneme_2": "/eɪ/",
        "description": "Phân biệt nguyên âm đơn /e/ và nguyên âm đôi /eɪ/. Người Việt hay phát âm /e/ thành /eɪ/.",
        "cefr_level": "A2",
        "order": 5,
        "pairs": [
            {"word": "bet",  "ipa": "/bet/",   "meaning": "cược"},
            {"word": "bait", "ipa": "/beɪt/",  "meaning": "mồi nhử"},
            {"word": "let",  "ipa": "/let/",   "meaning": "để / cho phép"},
            {"word": "late", "ipa": "/leɪt/",  "meaning": "muộn"},
            {"word": "wet",  "ipa": "/wet/",   "meaning": "ướt"},
            {"word": "wait", "ipa": "/weɪt/",  "meaning": "chờ đợi"},
            {"word": "get",  "ipa": "/ɡet/",   "meaning": "lấy / được"},
            {"word": "gate", "ipa": "/ɡeɪt/",  "meaning": "cổng"},
            {"word": "ten",  "ipa": "/ten/",   "meaning": "mười"},
            {"word": "tame", "ipa": "/teɪm/",  "meaning": "thuần phục"},
        ],
    },
    {
        "title": "/ɪ/ vs /e/ — bit / bet",
        "focus_phoneme_1": "/ɪ/",
        "focus_phoneme_2": "/e/",
        "description": "Phân biệt /ɪ/ (miệng hơi khép, lưỡi cao) và /e/ (miệng mở vừa, lưỡi giữa).",
        "cefr_level": "A1",
        "order": 6,
        "pairs": [
            {"word": "bit",  "ipa": "/bɪt/",  "meaning": "một chút"},
            {"word": "bet",  "ipa": "/bet/",  "meaning": "đặt cược"},
            {"word": "bin",  "ipa": "/bɪn/",  "meaning": "thùng rác"},
            {"word": "ben",  "ipa": "/ben/",  "meaning": "đỉnh núi (Scotland)"},
            {"word": "lid",  "ipa": "/lɪd/",  "meaning": "nắp đậy"},
            {"word": "led",  "ipa": "/led/",  "meaning": "đã dẫn đầu"},
            {"word": "will", "ipa": "/wɪl/",  "meaning": "sẽ"},
            {"word": "well", "ipa": "/wel/",  "meaning": "giếng / tốt"},
            {"word": "sit",  "ipa": "/sɪt/",  "meaning": "ngồi"},
            {"word": "set",  "ipa": "/set/",  "meaning": "đặt xuống"},
        ],
    },
    {
        "title": "/əʊ/ vs /ɒ/ — code / cod",
        "focus_phoneme_1": "/əʊ/",
        "focus_phoneme_2": "/ɒ/",
        "description": "Phân biệt nguyên âm đôi /əʊ/ và nguyên âm ngắn /ɒ/. Người Việt dễ phát âm giống nhau.",
        "cefr_level": "A2",
        "order": 7,
        "pairs": [
            {"word": "code", "ipa": "/kəʊd/",  "meaning": "mã code"},
            {"word": "cod",  "ipa": "/kɒd/",   "meaning": "cá tuyết"},
            {"word": "note", "ipa": "/nəʊt/",  "meaning": "ghi chú"},
            {"word": "not",  "ipa": "/nɒt/",   "meaning": "không"},
            {"word": "bone", "ipa": "/bəʊn/",  "meaning": "xương"},
            {"word": "bon",  "ipa": "/bɒn/",   "meaning": "tốt lành (Pháp)"},
            {"word": "coat", "ipa": "/kəʊt/",  "meaning": "áo khoác"},
            {"word": "cot",  "ipa": "/kɒt/",   "meaning": "giường trẻ em"},
            {"word": "robe", "ipa": "/rəʊb/",  "meaning": "áo choàng"},
            {"word": "rob",  "ipa": "/rɒb/",   "meaning": "cướp"},
        ],
    },
    # ── GROUP 2: Diphthongs ──────────────────────────────────────────────
    {
        "title": "/aɪ/ vs /eɪ/ — ride / raid",
        "focus_phoneme_1": "/aɪ/",
        "focus_phoneme_2": "/eɪ/",
        "description": "Phân biệt nguyên âm đôi /aɪ/ (âm xuất phát từ /a/) và /eɪ/ (âm xuất phát từ /e/).",
        "cefr_level": "B1",
        "order": 8,
        "pairs": [
            {"word": "ride",  "ipa": "/raɪd/",  "meaning": "cưỡi / lái"},
            {"word": "raid",  "ipa": "/reɪd/",  "meaning": "đột kích"},
            {"word": "mine",  "ipa": "/maɪn/",  "meaning": "của tôi"},
            {"word": "mane",  "ipa": "/meɪn/",  "meaning": "bờm ngựa"},
            {"word": "bite",  "ipa": "/baɪt/",  "meaning": "cắn"},
            {"word": "bait",  "ipa": "/beɪt/",  "meaning": "mồi nhử"},
            {"word": "fine",  "ipa": "/faɪn/",  "meaning": "tốt / phạt tiền"},
            {"word": "feign", "ipa": "/feɪn/",  "meaning": "giả vờ"},
            {"word": "tile",  "ipa": "/taɪl/",  "meaning": "gạch lát"},
            {"word": "tale",  "ipa": "/teɪl/",  "meaning": "câu chuyện"},
        ],
    },
    {
        "title": "/ɪə/ vs /eə/ — fear / fair",
        "focus_phoneme_1": "/ɪə/",
        "focus_phoneme_2": "/eə/",
        "description": "Phân biệt /ɪə/ (ear) và /eə/ (air). Hai âm này rất khó phân biệt với người Việt.",
        "cefr_level": "B1",
        "order": 9,
        "pairs": [
            {"word": "fear",  "ipa": "/fɪə/",  "meaning": "sợ hãi"},
            {"word": "fair",  "ipa": "/feə/",  "meaning": "công bằng"},
            {"word": "ear",   "ipa": "/ɪə/",   "meaning": "tai"},
            {"word": "air",   "ipa": "/eə/",   "meaning": "không khí"},
            {"word": "here",  "ipa": "/hɪə/",  "meaning": "ở đây"},
            {"word": "hair",  "ipa": "/heə/",  "meaning": "tóc"},
            {"word": "beer",  "ipa": "/bɪə/",  "meaning": "bia"},
            {"word": "bare",  "ipa": "/beə/",  "meaning": "trần trụi"},
            {"word": "near",  "ipa": "/nɪə/",  "meaning": "gần"},
            {"word": "mare",  "ipa": "/meə/",  "meaning": "ngựa cái"},
        ],
    },
    # ── GROUP 3: TH Sounds (very hard for Vietnamese) ────────────────────
    {
        "title": "/θ/ vs /s/ — think / sink",
        "focus_phoneme_1": "/θ/",
        "focus_phoneme_2": "/s/",
        "description": "Phân biệt /θ/ (lưỡi chạm răng trên) và /s/ (lưỡi không chạm răng). Người Việt thường phát âm /θ/ thành /s/.",
        "cefr_level": "A1",
        "order": 10,
        "pairs": [
            {"word": "think",   "ipa": "/θɪŋk/",  "meaning": "nghĩ"},
            {"word": "sink",    "ipa": "/sɪŋk/",  "meaning": "chìm / bồn rửa"},
            {"word": "three",   "ipa": "/θriː/",   "meaning": "ba"},
            {"word": "see",     "ipa": "/siː/",    "meaning": "nhìn thấy"},
            {"word": "thick",   "ipa": "/θɪk/",   "meaning": "dày"},
            {"word": "sick",    "ipa": "/sɪk/",   "meaning": "ốm"},
            {"word": "thin",    "ipa": "/θɪn/",   "meaning": "mỏng"},
            {"word": "sin",     "ipa": "/sɪn/",   "meaning": "tội lỗi"},
            {"word": "thought", "ipa": "/θɔːt/",  "meaning": "suy nghĩ (quá khứ)"},
            {"word": "sort",    "ipa": "/sɔːt/",  "meaning": "loại / sắp xếp"},
        ],
    },
    {
        "title": "/θ/ vs /t/ — think / tink",
        "focus_phoneme_1": "/θ/",
        "focus_phoneme_2": "/t/",
        "description": "Phân biệt /θ/ (lưỡi nhô ra giữa răng) và /t/ (lưỡi chạm vòm miệng). Người Việt thường thay /θ/ bằng /t/.",
        "cefr_level": "A2",
        "order": 11,
        "pairs": [
            {"word": "think",  "ipa": "/θɪŋk/",   "meaning": "nghĩ"},
            {"word": "tink",   "ipa": "/tɪŋk/",    "meaning": "kêu leng keng"},
            {"word": "thank",  "ipa": "/θæŋk/",   "meaning": "cảm ơn"},
            {"word": "tank",   "ipa": "/tæŋk/",   "meaning": "xe tăng / bể"},
            {"word": "thick",  "ipa": "/θɪk/",    "meaning": "dày"},
            {"word": "tick",   "ipa": "/tɪk/",    "meaning": "tích / đánh dấu"},
            {"word": "three",  "ipa": "/θriː/",    "meaning": "ba"},
            {"word": "tree",   "ipa": "/triː/",    "meaning": "cây"},
            {"word": "bath",   "ipa": "/bɑːθ/",   "meaning": "bồn tắm"},
            {"word": "bat",    "ipa": "/bæt/",    "meaning": "con dơi / cây gậy"},
        ],
    },
    {
        "title": "/ð/ vs /d/ — this / dis",
        "focus_phoneme_1": "/ð/",
        "focus_phoneme_2": "/d/",
        "description": "Phân biệt /ð/ (hữu thanh, lưỡi giữa răng) và /d/ (lưỡi chạm vòm). Người Việt thường phát âm /ð/ thành /d/.",
        "cefr_level": "A1",
        "order": 12,
        "pairs": [
            {"word": "this",    "ipa": "/ðɪs/",    "meaning": "cái này"},
            {"word": "dis",     "ipa": "/dɪs/",    "meaning": "khinh thường"},
            {"word": "they",    "ipa": "/ðeɪ/",    "meaning": "họ"},
            {"word": "day",     "ipa": "/deɪ/",    "meaning": "ngày"},
            {"word": "though",  "ipa": "/ðəʊ/",    "meaning": "mặc dù"},
            {"word": "doe",     "ipa": "/dəʊ/",    "meaning": "nai cái"},
            {"word": "then",    "ipa": "/ðen/",    "meaning": "sau đó"},
            {"word": "den",     "ipa": "/den/",    "meaning": "hang ổ"},
            {"word": "breathe", "ipa": "/briːð/",  "meaning": "thở (động từ)"},
            {"word": "breed",   "ipa": "/briːd/",  "meaning": "giống / nhân giống"},
        ],
    },
    {
        "title": "/ð/ vs /z/ — clothing / closing",
        "focus_phoneme_1": "/ð/",
        "focus_phoneme_2": "/z/",
        "description": "Phân biệt /ð/ (lưỡi giữa răng, hơi) và /z/ (lưỡi gần răng, rít). Thường nhầm lẫn trong các từ như 'the', 'then'.",
        "cefr_level": "A2",
        "order": 13,
        "pairs": [
            {"word": "that",    "ipa": "/ðæt/",    "meaning": "cái đó"},
            {"word": "zat",     "ipa": "/zæt/",    "meaning": "(từ không có nghĩa)"},
            {"word": "they",    "ipa": "/ðeɪ/",    "meaning": "họ"},
            {"word": "zey",     "ipa": "/zeɪ/",    "meaning": "(phát âm sai của they)"},
            {"word": "loathe",  "ipa": "/ləʊð/",   "meaning": "ghét cay"},
            {"word": "lows",    "ipa": "/ləʊz/",   "meaning": "âm nhạc thấp"},
            {"word": "seethe",  "ipa": "/siːð/",   "meaning": "sôi giận"},
            {"word": "seize",   "ipa": "/siːz/",   "meaning": "chiếm lấy"},
            {"word": "teethe",  "ipa": "/tiːð/",   "meaning": "mọc răng"},
            {"word": "tees",    "ipa": "/tiːz/",   "meaning": "gậy golf nhỏ"},
        ],
    },
    # ── GROUP 4: L / R (hardest for Vietnamese) ──────────────────────────
    {
        "title": "/l/ vs /r/ — law / raw",
        "focus_phoneme_1": "/l/",
        "focus_phoneme_2": "/r/",
        "description": "Phân biệt /l/ (đầu lưỡi chạm vòm miệng) và /r/ (lưỡi co lại, không chạm). Đây là cặp KHÓ NHẤT với người Việt!",
        "cefr_level": "A1",
        "order": 14,
        "pairs": [
            {"word": "law",   "ipa": "/lɔː/",   "meaning": "luật pháp"},
            {"word": "raw",   "ipa": "/rɔː/",   "meaning": "thô, sống"},
            {"word": "lake",  "ipa": "/leɪk/",  "meaning": "hồ"},
            {"word": "rake",  "ipa": "/reɪk/",  "meaning": "cào cỏ"},
            {"word": "lice",  "ipa": "/laɪs/",  "meaning": "con rận"},
            {"word": "rice",  "ipa": "/raɪs/",  "meaning": "cơm / gạo"},
            {"word": "light", "ipa": "/laɪt/",  "meaning": "ánh sáng"},
            {"word": "right", "ipa": "/raɪt/",  "meaning": "đúng / phải"},
            {"word": "glass", "ipa": "/ɡlɑːs/", "meaning": "ly thủy tinh"},
            {"word": "grass", "ipa": "/ɡrɑːs/", "meaning": "cỏ"},
        ],
    },
    {
        "title": "/l/ vs /r/ — play / pray",
        "focus_phoneme_1": "/l/",
        "focus_phoneme_2": "/r/",
        "description": "Cặp /l/ vs /r/ trong nhóm phụ âm kép (clusters). Đặc biệt khó phát âm với từ có bl/br, fl/fr, pl/pr, cl/cr.",
        "cefr_level": "A2",
        "order": 15,
        "pairs": [
            {"word": "play",   "ipa": "/pleɪ/",  "meaning": "chơi / phát"},
            {"word": "pray",   "ipa": "/preɪ/",  "meaning": "cầu nguyện"},
            {"word": "claim",  "ipa": "/kleɪm/", "meaning": "đòi / yêu cầu"},
            {"word": "cream",  "ipa": "/kriːm/", "meaning": "kem"},
            {"word": "flay",   "ipa": "/fleɪ/",  "meaning": "lột da"},
            {"word": "fray",   "ipa": "/freɪ/",  "meaning": "sờn / xây xát"},
            {"word": "cloud",  "ipa": "/klaʊd/", "meaning": "đám mây"},
            {"word": "crowd",  "ipa": "/kraʊd/", "meaning": "đám đông"},
            {"word": "flee",   "ipa": "/fliː/",  "meaning": "bỏ chạy"},
            {"word": "free",   "ipa": "/friː/",  "meaning": "tự do"},
        ],
    },
    # ── GROUP 5: V / B / W ────────────────────────────────────────────────
    {
        "title": "/v/ vs /b/ — van / ban",
        "focus_phoneme_1": "/v/",
        "focus_phoneme_2": "/b/",
        "description": "Phân biệt /v/ (răng cắn môi dưới, hơi thoát) và /b/ (hai môi khép). Người Việt thường phát âm /v/ thành /b/ hoặc /z/.",
        "cefr_level": "A1",
        "order": 16,
        "pairs": [
            {"word": "van",   "ipa": "/væn/",   "meaning": "xe tải nhỏ"},
            {"word": "ban",   "ipa": "/bæn/",   "meaning": "cấm"},
            {"word": "very",  "ipa": "/ˈveri/", "meaning": "rất"},
            {"word": "berry", "ipa": "/ˈberi/", "meaning": "quả mọng"},
            {"word": "vest",  "ipa": "/vest/",  "meaning": "áo gi lê"},
            {"word": "best",  "ipa": "/best/",  "meaning": "tốt nhất"},
            {"word": "vine",  "ipa": "/vaɪn/",  "meaning": "dây leo"},
            {"word": "bine",  "ipa": "/baɪn/",  "meaning": "cây leo"},
            {"word": "vote",  "ipa": "/vəʊt/",  "meaning": "phiếu bầu"},
            {"word": "boat",  "ipa": "/bəʊt/",  "meaning": "thuyền"},
        ],
    },
    {
        "title": "/w/ vs /v/ — wine / vine",
        "focus_phoneme_1": "/w/",
        "focus_phoneme_2": "/v/",
        "description": "Phân biệt /w/ (môi tron tròn, không chạm răng) và /v/ (răng trên chạm môi dưới). Người Việt dễ nhầm lẫn hai âm này.",
        "cefr_level": "A2",
        "order": 17,
        "pairs": [
            {"word": "wine",  "ipa": "/waɪn/",  "meaning": "rượu vang"},
            {"word": "vine",  "ipa": "/vaɪn/",  "meaning": "dây leo"},
            {"word": "west",  "ipa": "/west/",  "meaning": "phía tây"},
            {"word": "vest",  "ipa": "/vest/",  "meaning": "áo gi lê"},
            {"word": "wet",   "ipa": "/wet/",   "meaning": "ướt"},
            {"word": "vet",   "ipa": "/vet/",   "meaning": "bác sĩ thú y"},
            {"word": "wary",  "ipa": "/ˈweəri/","meaning": "cảnh giác"},
            {"word": "vary",  "ipa": "/ˈveəri/","meaning": "thay đổi"},
            {"word": "wiper", "ipa": "/ˈwaɪpə/","meaning": "gạt nước"},
            {"word": "viper", "ipa": "/ˈvaɪpə/","meaning": "rắn độc"},
        ],
    },
    # ── GROUP 6: P / F / B ────────────────────────────────────────────────
    {
        "title": "/p/ vs /f/ — pan / fan",
        "focus_phoneme_1": "/p/",
        "focus_phoneme_2": "/f/",
        "description": "Phân biệt /p/ (hai môi phát nổ) và /f/ (răng cắn môi dưới, hơi thoát liên tục).",
        "cefr_level": "A1",
        "order": 18,
        "pairs": [
            {"word": "pan",   "ipa": "/pæn/",   "meaning": "chảo / chậu"},
            {"word": "fan",   "ipa": "/fæn/",   "meaning": "quạt / người hâm mộ"},
            {"word": "pin",   "ipa": "/pɪn/",   "meaning": "cái kim"},
            {"word": "fin",   "ipa": "/fɪn/",   "meaning": "vây cá"},
            {"word": "pace",  "ipa": "/peɪs/",  "meaning": "tốc độ"},
            {"word": "face",  "ipa": "/feɪs/",  "meaning": "khuôn mặt"},
            {"word": "peel",  "ipa": "/piːl/",  "meaning": "bóc vỏ"},
            {"word": "feel",  "ipa": "/fiːl/",  "meaning": "cảm thấy"},
            {"word": "pest",  "ipa": "/pest/",  "meaning": "loài gây hại"},
            {"word": "fest",  "ipa": "/fest/",  "meaning": "lễ hội"},
        ],
    },
    {
        "title": "/p/ vs /b/ — pat / bat",
        "focus_phoneme_1": "/p/",
        "focus_phoneme_2": "/b/",
        "description": "Phân biệt /p/ (vô thanh, nổ) và /b/ (hữu thanh, nổ nhẹ). Người Việt dễ nhầm lẫn ở cuối từ.",
        "cefr_level": "A1",
        "order": 19,
        "pairs": [
            {"word": "pat",  "ipa": "/pæt/",  "meaning": "vỗ nhẹ"},
            {"word": "bat",  "ipa": "/bæt/",  "meaning": "con dơi / gậy bóng"},
            {"word": "pin",  "ipa": "/pɪn/",  "meaning": "cái kim"},
            {"word": "bin",  "ipa": "/bɪn/",  "meaning": "thùng rác"},
            {"word": "cap",  "ipa": "/kæp/",  "meaning": "mũ lưỡi trai"},
            {"word": "cab",  "ipa": "/kæb/",  "meaning": "taxi"},
            {"word": "cup",  "ipa": "/kʌp/",  "meaning": "cái ly"},
            {"word": "cub",  "ipa": "/kʌb/",  "meaning": "gấu con"},
            {"word": "tap",  "ipa": "/tæp/",  "meaning": "vòi nước"},
            {"word": "tab",  "ipa": "/tæb/",  "meaning": "tab / phiếu"},
        ],
    },
    # ── GROUP 7: T / D / N / NG ───────────────────────────────────────────
    {
        "title": "/t/ vs /d/ — ten / den",
        "focus_phoneme_1": "/t/",
        "focus_phoneme_2": "/d/",
        "description": "Phân biệt /t/ (vô thanh) và /d/ (hữu thanh). Đặc biệt quan trọng ở cuối từ — người Việt thường không phát âm phụ âm cuối.",
        "cefr_level": "A1",
        "order": 20,
        "pairs": [
            {"word": "ten",  "ipa": "/ten/",   "meaning": "mười"},
            {"word": "den",  "ipa": "/den/",   "meaning": "hang / phòng"},
            {"word": "tie",  "ipa": "/taɪ/",   "meaning": "cravat / buộc"},
            {"word": "die",  "ipa": "/daɪ/",   "meaning": "chết"},
            {"word": "bat",  "ipa": "/bæt/",   "meaning": "con dơi"},
            {"word": "bad",  "ipa": "/bæd/",   "meaning": "xấu"},
            {"word": "hat",  "ipa": "/hæt/",   "meaning": "mũ"},
            {"word": "had",  "ipa": "/hæd/",   "meaning": "đã có"},
            {"word": "seat", "ipa": "/siːt/",  "meaning": "ghế"},
            {"word": "seed", "ipa": "/siːd/",  "meaning": "hạt giống"},
        ],
    },
    {
        "title": "/n/ vs /ŋ/ — sin / sing",
        "focus_phoneme_1": "/n/",
        "focus_phoneme_2": "/ŋ/",
        "description": "Phân biệt /n/ (lưỡi chạm vòm) và /ŋ/ (lưỡi chạm vòm mềm). Người Việt hay đọc -ng thành -n.",
        "cefr_level": "A2",
        "order": 21,
        "pairs": [
            {"word": "sin",   "ipa": "/sɪn/",   "meaning": "tội lỗi"},
            {"word": "sing",  "ipa": "/sɪŋ/",   "meaning": "hát"},
            {"word": "win",   "ipa": "/wɪn/",   "meaning": "thắng"},
            {"word": "wing",  "ipa": "/wɪŋ/",   "meaning": "cánh"},
            {"word": "ban",   "ipa": "/bæn/",   "meaning": "cấm"},
            {"word": "bang",  "ipa": "/bæŋ/",   "meaning": "tiếng nổ"},
            {"word": "fan",   "ipa": "/fæn/",   "meaning": "quạt"},
            {"word": "fang",  "ipa": "/fæŋ/",   "meaning": "nanh"},
            {"word": "thin",  "ipa": "/θɪn/",   "meaning": "mỏng"},
            {"word": "thing", "ipa": "/θɪŋ/",   "meaning": "vật / điều"},
        ],
    },
    # ── GROUP 8: S / Z / Final sounds ─────────────────────────────────────
    {
        "title": "/s/ vs /z/ — race / raise",
        "focus_phoneme_1": "/s/",
        "focus_phoneme_2": "/z/",
        "description": "Phân biệt /s/ (vô thanh, rít nhẹ) và /z/ (hữu thanh, rít nặng hơn). Thường xuất hiện ở cuối từ.",
        "cefr_level": "A2",
        "order": 22,
        "pairs": [
            {"word": "race",  "ipa": "/reɪs/",  "meaning": "đua"},
            {"word": "raise", "ipa": "/reɪz/",  "meaning": "nâng lên"},
            {"word": "price", "ipa": "/praɪs/", "meaning": "giá"},
            {"word": "prize", "ipa": "/praɪz/", "meaning": "giải thưởng"},
            {"word": "ice",   "ipa": "/aɪs/",   "meaning": "nước đá"},
            {"word": "eyes",  "ipa": "/aɪz/",   "meaning": "đôi mắt"},
            {"word": "bus",   "ipa": "/bʌs/",   "meaning": "xe buýt"},
            {"word": "buzz",  "ipa": "/bʌz/",   "meaning": "vo ve"},
            {"word": "lace",  "ipa": "/leɪs/",  "meaning": "ren đăng ten"},
            {"word": "laze",  "ipa": "/leɪz/",  "meaning": "lười biếng"},
        ],
    },
    {
        "title": "/k/ vs /g/ — coat / goat",
        "focus_phoneme_1": "/k/",
        "focus_phoneme_2": "/ɡ/",
        "description": "Phân biệt /k/ (vô thanh) và /g/ (hữu thanh). Cũng quan trọng ở cuối từ.",
        "cefr_level": "A1",
        "order": 23,
        "pairs": [
            {"word": "coat",  "ipa": "/kəʊt/",  "meaning": "áo khoác"},
            {"word": "goat",  "ipa": "/ɡəʊt/",  "meaning": "con dê"},
            {"word": "cap",   "ipa": "/kæp/",   "meaning": "mũ"},
            {"word": "gap",   "ipa": "/ɡæp/",   "meaning": "khoảng cách"},
            {"word": "back",  "ipa": "/bæk/",   "meaning": "lưng / phía sau"},
            {"word": "bag",   "ipa": "/bæɡ/",   "meaning": "túi xách"},
            {"word": "lock",  "ipa": "/lɒk/",   "meaning": "khóa"},
            {"word": "log",   "ipa": "/lɒɡ/",   "meaning": "khúc gỗ"},
            {"word": "pick",  "ipa": "/pɪk/",   "meaning": "nhặt / chọn"},
            {"word": "pig",   "ipa": "/pɪɡ/",   "meaning": "con lợn"},
        ],
    },
    # ── GROUP 9: CH / SH / J ──────────────────────────────────────────────
    {
        "title": "/tʃ/ vs /ʃ/ — cheap / sheep",
        "focus_phoneme_1": "/tʃ/",
        "focus_phoneme_2": "/ʃ/",
        "description": "Phân biệt /tʃ/ (ch, kết hợp t+sh) và /ʃ/ (sh, chỉ là sh đơn thuần). Người Việt thường phát âm cả hai giống /sh/.",
        "cefr_level": "A2",
        "order": 24,
        "pairs": [
            {"word": "cheap",  "ipa": "/tʃiːp/",  "meaning": "rẻ"},
            {"word": "sheep",  "ipa": "/ʃiːp/",   "meaning": "con cừu"},
            {"word": "chin",   "ipa": "/tʃɪn/",   "meaning": "cằm"},
            {"word": "shin",   "ipa": "/ʃɪn/",    "meaning": "ống chân"},
            {"word": "cheat",  "ipa": "/tʃiːt/",  "meaning": "gian lận"},
            {"word": "sheet",  "ipa": "/ʃiːt/",   "meaning": "tờ giấy"},
            {"word": "watch",  "ipa": "/wɒtʃ/",   "meaning": "xem / đồng hồ"},
            {"word": "wash",   "ipa": "/wɒʃ/",    "meaning": "rửa"},
            {"word": "match",  "ipa": "/mætʃ/",   "meaning": "trận đấu"},
            {"word": "mash",   "ipa": "/mæʃ/",    "meaning": "nghiền nát"},
        ],
    },
    {
        "title": "/dʒ/ vs /j/ — jet / yet",
        "focus_phoneme_1": "/dʒ/",
        "focus_phoneme_2": "/j/",
        "description": "Phân biệt /dʒ/ (j, âm nổ + xì) và /j/ (y trong 'yes', trơn không nổ).",
        "cefr_level": "A2",
        "order": 25,
        "pairs": [
            {"word": "jet",    "ipa": "/dʒet/",    "meaning": "máy bay phản lực"},
            {"word": "yet",    "ipa": "/jet/",     "meaning": "chưa / vẫn"},
            {"word": "jell",   "ipa": "/dʒel/",    "meaning": "đóng keo"},
            {"word": "yell",   "ipa": "/jel/",     "meaning": "la hét"},
            {"word": "joke",   "ipa": "/dʒəʊk/",  "meaning": "trò đùa"},
            {"word": "yoke",   "ipa": "/jəʊk/",   "meaning": "ách / thắt lại"},
            {"word": "Jack",   "ipa": "/dʒæk/",   "meaning": "tên người"},
            {"word": "yak",    "ipa": "/jæk/",    "meaning": "trâu yak (gần đây dùng /j/)"},
            {"word": "jeer",   "ipa": "/dʒɪə/",   "meaning": "chế giễu"},
            {"word": "year",   "ipa": "/jɪə/",    "meaning": "năm"},
        ],
    },
    # ── GROUP 10: Word-Final Consonants ──────────────────────────────────
    {
        "title": "Cuối từ /p/ vs /b/ — cap / cab",
        "focus_phoneme_1": "/p/ (cuối)",
        "focus_phoneme_2": "/b/ (cuối)",
        "description": "Phân biệt phụ âm cuối /p/ (vô thanh) và /b/ (hữu thanh). Tiếng Việt không có phụ âm cuối nên rất dễ bỏ qua sự khác biệt này.",
        "cefr_level": "A2",
        "order": 26,
        "pairs": [
            {"word": "cap",   "ipa": "/kæp/",   "meaning": "mũ lưỡi trai"},
            {"word": "cab",   "ipa": "/kæb/",   "meaning": "taxi"},
            {"word": "cup",   "ipa": "/kʌp/",   "meaning": "cái ly"},
            {"word": "cub",   "ipa": "/kʌb/",   "meaning": "gấu con"},
            {"word": "rope",  "ipa": "/rəʊp/",  "meaning": "dây thừng"},
            {"word": "robe",  "ipa": "/rəʊb/",  "meaning": "áo choàng"},
            {"word": "tap",   "ipa": "/tæp/",   "meaning": "vòi nước"},
            {"word": "tab",   "ipa": "/tæb/",   "meaning": "tab / phiếu"},
            {"word": "heap",  "ipa": "/hiːp/",  "meaning": "đống"},
            {"word": "heave", "ipa": "/hiːv/",  "meaning": "kéo mạnh"},
        ],
    },
    {
        "title": "Cuối từ /t/ vs /d/ — bat / bad",
        "focus_phoneme_1": "/t/ (cuối)",
        "focus_phoneme_2": "/d/ (cuối)",
        "description": "Phân biệt /t/ và /d/ ở cuối từ. Người Việt thường không phát âm âm cuối, dẫn đến hiểu nhầm.",
        "cefr_level": "A2",
        "order": 27,
        "pairs": [
            {"word": "bat",   "ipa": "/bæt/",   "meaning": "con dơi"},
            {"word": "bad",   "ipa": "/bæd/",   "meaning": "xấu"},
            {"word": "cat",   "ipa": "/kæt/",   "meaning": "con mèo"},
            {"word": "cad",   "ipa": "/kæd/",   "meaning": "kẻ vô lại"},
            {"word": "heart", "ipa": "/hɑːt/",  "meaning": "trái tim"},
            {"word": "hard",  "ipa": "/hɑːd/",  "meaning": "cứng / khó"},
            {"word": "coat",  "ipa": "/kəʊt/",  "meaning": "áo khoác"},
            {"word": "code",  "ipa": "/kəʊd/",  "meaning": "mã code"},
            {"word": "late",  "ipa": "/leɪt/",  "meaning": "trễ"},
            {"word": "laid",  "ipa": "/leɪd/",  "meaning": "đã đặt"},
        ],
    },
    {
        "title": "Cuối từ /f/ vs /v/ — leaf / leave",
        "focus_phoneme_1": "/f/ (cuối)",
        "focus_phoneme_2": "/v/ (cuối)",
        "description": "Phân biệt /f/ (vô thanh) và /v/ (hữu thanh) ở cuối từ. Khó vì người Việt không quen với phụ âm cuối.",
        "cefr_level": "B1",
        "order": 28,
        "pairs": [
            {"word": "leaf",   "ipa": "/liːf/",   "meaning": "chiếc lá"},
            {"word": "leave",  "ipa": "/liːv/",   "meaning": "rời đi"},
            {"word": "safe",   "ipa": "/seɪf/",   "meaning": "an toàn"},
            {"word": "save",   "ipa": "/seɪv/",   "meaning": "lưu / tiết kiệm"},
            {"word": "proof",  "ipa": "/pruːf/",  "meaning": "bằng chứng"},
            {"word": "prove",  "ipa": "/pruːv/",  "meaning": "chứng minh"},
            {"word": "grief",  "ipa": "/ɡriːf/",  "meaning": "nỗi đau"},
            {"word": "grieve", "ipa": "/ɡriːv/",  "meaning": "đau buồn"},
            {"word": "half",   "ipa": "/hɑːf/",   "meaning": "một nửa"},
            {"word": "halve",  "ipa": "/hɑːv/",   "meaning": "chia đôi"},
        ],
    },
    {
        "title": "Cuối từ /k/ vs /g/ — back / bag",
        "focus_phoneme_1": "/k/ (cuối)",
        "focus_phoneme_2": "/ɡ/ (cuối)",
        "description": "Phân biệt phụ âm cuối /k/ và /g/. Cực kỳ quan trọng khi giao tiếp vì dễ hiểu nhầm.",
        "cefr_level": "A2",
        "order": 29,
        "pairs": [
            {"word": "back",  "ipa": "/bæk/",  "meaning": "lưng / phía sau"},
            {"word": "bag",   "ipa": "/bæɡ/",  "meaning": "túi xách"},
            {"word": "lock",  "ipa": "/lɒk/",  "meaning": "khóa"},
            {"word": "log",   "ipa": "/lɒɡ/",  "meaning": "khúc gỗ"},
            {"word": "dock",  "ipa": "/dɒk/",  "meaning": "bến cảng"},
            {"word": "dog",   "ipa": "/dɒɡ/",  "meaning": "con chó"},
            {"word": "lack",  "ipa": "/læk/",  "meaning": "thiếu"},
            {"word": "lag",   "ipa": "/læɡ/",  "meaning": "chậm lại"},
            {"word": "pick",  "ipa": "/pɪk/",  "meaning": "chọn lựa"},
            {"word": "pig",   "ipa": "/pɪɡ/",  "meaning": "con lợn"},
        ],
    },
    # ── GROUP 11: Advanced / B1-B2 ────────────────────────────────────────
    {
        "title": "/æ/ vs /ɑː/ — cat / cart",
        "focus_phoneme_1": "/æ/",
        "focus_phoneme_2": "/ɑː/",
        "description": "Phân biệt /æ/ (miệng mở rộng, lưỡi thấp phía trước) và /ɑː/ (miệng mở rộng, lưỡi thấp phía sau).",
        "cefr_level": "B1",
        "order": 30,
        "pairs": [
            {"word": "cat",   "ipa": "/kæt/",   "meaning": "con mèo"},
            {"word": "cart",  "ipa": "/kɑːt/",  "meaning": "xe đẩy"},
            {"word": "bat",   "ipa": "/bæt/",   "meaning": "con dơi"},
            {"word": "bar",   "ipa": "/bɑː/",   "meaning": "quán bar"},
            {"word": "man",   "ipa": "/mæn/",   "meaning": "người đàn ông"},
            {"word": "mar",   "ipa": "/mɑː/",   "meaning": "làm hỏng"},
            {"word": "pat",   "ipa": "/pæt/",   "meaning": "vỗ nhẹ"},
            {"word": "part",  "ipa": "/pɑːt/",  "meaning": "phần / vai trò"},
            {"word": "bad",   "ipa": "/bæd/",   "meaning": "xấu"},
            {"word": "bard",  "ipa": "/bɑːd/",  "meaning": "thi sĩ"},
        ],
    },
    {
        "title": "/ɜː/ vs /ɔː/ — bird / board",
        "focus_phoneme_1": "/ɜː/",
        "focus_phoneme_2": "/ɔː/",
        "description": "Phân biệt /ɜː/ (er trong bird) và /ɔː/ (or trong board). Cả hai đều là nguyên âm dài nhưng khác vị trí miệng.",
        "cefr_level": "B1",
        "order": 31,
        "pairs": [
            {"word": "bird",   "ipa": "/bɜːd/",  "meaning": "con chim"},
            {"word": "board",  "ipa": "/bɔːd/",  "meaning": "bảng"},
            {"word": "her",    "ipa": "/hɜː/",   "meaning": "cô ấy (túc từ)"},
            {"word": "haw",    "ipa": "/hɔː/",   "meaning": "quả táo gai"},
            {"word": "fern",   "ipa": "/fɜːn/",  "meaning": "cây dương xỉ"},
            {"word": "fawn",   "ipa": "/fɔːn/",  "meaning": "nai non"},
            {"word": "burn",   "ipa": "/bɜːn/",  "meaning": "đốt cháy"},
            {"word": "born",   "ipa": "/bɔːn/",  "meaning": "được sinh ra"},
            {"word": "stir",   "ipa": "/stɜː/",  "meaning": "khuấy"},
            {"word": "store",  "ipa": "/stɔː/",  "meaning": "cửa hàng"},
        ],
    },
    {
        "title": "/aʊ/ vs /ɔː/ — loud / laud",
        "focus_phoneme_1": "/aʊ/",
        "focus_phoneme_2": "/ɔː/",
        "description": "Phân biệt nguyên âm đôi /aʊ/ (bắt đầu từ /a/) và nguyên âm đơn dài /ɔː/.",
        "cefr_level": "B1",
        "order": 32,
        "pairs": [
            {"word": "loud",   "ipa": "/laʊd/",  "meaning": "ồn ào"},
            {"word": "laud",   "ipa": "/lɔːd/",  "meaning": "ca ngợi"},
            {"word": "found",  "ipa": "/faʊnd/", "meaning": "tìm thấy"},
            {"word": "fawned", "ipa": "/fɔːnd/", "meaning": "nịnh bợ (quá khứ)"},
            {"word": "bout",   "ipa": "/baʊt/",  "meaning": "trận đấu"},
            {"word": "bought", "ipa": "/bɔːt/",  "meaning": "đã mua"},
            {"word": "cow",    "ipa": "/kaʊ/",   "meaning": "con bò cái"},
            {"word": "caw",    "ipa": "/kɔː/",   "meaning": "tiếng quạ kêu"},
            {"word": "how",    "ipa": "/haʊ/",   "meaning": "như thế nào"},
            {"word": "haw",    "ipa": "/hɔː/",   "meaning": "quả táo gai"},
        ],
    },
]


class Command(BaseCommand):
    help = "Seed minimal pair sets and pairs for pronunciation practice"

    def add_arguments(self, parser):
        parser.add_argument(
            "--clear",
            action="store_true",
            help="Delete ALL existing minimal pair sets before seeding",
        )

    def handle(self, *args, **options):
        if options["clear"]:
            count = MinimalPairSet.objects.count()
            MinimalPairSet.objects.all().delete()
            self.stdout.write(self.style.WARNING(f"Deleted {count} existing minimal pair sets."))

        created_sets = 0
        created_pairs = 0
        skipped = 0

        for data in MINIMAL_PAIRS_DATA:
            title = data["title"]
            pairs_data = data.pop("pairs")

            set_obj, created = MinimalPairSet.objects.get_or_create(
                title=title,
                defaults={
                    "focus_phoneme_1": data["focus_phoneme_1"],
                    "focus_phoneme_2": data["focus_phoneme_2"],
                    "description": data["description"],
                    "cefr_level": data["cefr_level"],
                    "order": data.get("order", 0),
                    "is_published": True,
                },
            )

            if not created:
                skipped += 1
                self.stdout.write(f"  SKIP (exists): {title}")
                continue

            for idx, pair in enumerate(pairs_data):
                MinimalPair.objects.create(
                    pair_set=set_obj,
                    word=pair["word"],
                    ipa=pair["ipa"],
                    meaning=pair["meaning"],
                    order=idx,
                )
                created_pairs += 1

            created_sets += 1
            self.stdout.write(
                self.style.SUCCESS(f"  ✓ Created: {title} ({len(pairs_data)} pairs)")
            )

        self.stdout.write("")
        self.stdout.write(
            self.style.SUCCESS(
                f"Done! Created {created_sets} sets ({created_pairs} pairs). "
                f"Skipped {skipped} existing."
            )
        )
