# Generated by Django 5.0.3 on 2026-03-24 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tên quy tắc (VD: Câu khẳng định)', max_length=255)),
                ('formula', models.CharField(blank=True, help_text='Công thức ngắn gọn. VD: S + V(s/es) + Object', max_length=500)),
                ('explanation', models.TextField(help_text='Giải thích chi tiết cách dùng (hỗ trợ Markdown/HTML).')),
                ('memory_hook', models.TextField(blank=True, help_text='Câu ngắn gọn/hài hước giúp học viên nhớ quy tắc này ngay lập tức.', verbose_name='Mẹo nhớ quy tắc')),
                ('is_exception', models.BooleanField(default=False, help_text='Đánh dấu nếu đây là ngoại lệ (hiển thị cảnh báo đỏ trên UI).')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Quy tắc Ngữ pháp',
                'db_table': 'grammar_rule',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GrammarExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(help_text='Câu ví dụ tiếng Anh', max_length=500)),
                ('translation', models.CharField(blank=True, help_text='Dịch nghĩa tiếng Việt', max_length=500)),
                ('context', models.CharField(blank=True, help_text="Tình huống cụ thể giúp học viên cảm nhận câu. VD: 'Khi đang ngạc nhiên', 'Nói khẽ để không đánh thức em bé'", max_length=255, verbose_name='Ngữ cảnh cảm xúc')),
                ('highlight', models.CharField(blank=True, help_text="Từ/cụm từ cần tô màu trong câu (VD: 'is sleeping', 'goes').", max_length=150)),
                ('audio_url', models.URLField(blank=True, help_text='Link file âm thanh (S3 key hoặc URL CDN).', null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='grammar.grammarrule')),
            ],
            options={
                'verbose_name': 'Ví dụ Ngữ pháp',
                'db_table': 'grammar_example',
            },
        ),
        migrations.CreateModel(
            name='GrammarTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tên chủ đề (VD: Present Simple Tense)', max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('level', models.CharField(choices=[('A1', 'A1 — Beginner'), ('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper Intermediate'), ('C1', 'C1 — Advanced'), ('C2', 'C2 — Proficiency')], db_index=True, default='A1', max_length=2)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('icon', models.CharField(default='📚', help_text='Emoji hoặc mã class FontAwesome đại diện cho chủ đề', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Mô tả ngắn gọn chủ đề (dùng làm meta description)')),
                ('analogy', models.TextField(blank=True, help_text="So sánh cấu trúc ngữ pháp với khái niệm đời thường dễ hiểu. VD: 'Động từ to be giống như dấu bằng (=) trong toán học.'", verbose_name='Phép ẩn dụ (Analogy)')),
                ('real_world_use', models.TextField(blank=True, help_text='Giải thích tại sao học viên cần học chủ đề này trong thực tế.', verbose_name='Ứng dụng thực tế')),
                ('memory_hook', models.TextField(blank=True, help_text='Câu thần chú ngắn để nhớ toàn bộ chủ đề.', verbose_name='Mẹo nhớ tổng quát')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(blank=True, help_text='Bài học trong curriculum tương ứng với chủ đề này', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grammar_topic', to='curriculum.lesson')),
            ],
            options={
                'verbose_name': 'Chủ đề Ngữ pháp',
                'verbose_name_plural': 'Danh sách Chủ đề Ngữ pháp',
                'db_table': 'grammar_topic',
                'ordering': ['level', 'order'],
            },
        ),
        migrations.AddField(
            model_name='grammarrule',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='grammar.grammartopic'),
        ),
        migrations.AddIndex(
            model_name='grammartopic',
            index=models.Index(fields=['level', 'order'], name='grammar_top_level_119469_idx'),
        ),
        migrations.AddIndex(
            model_name='grammartopic',
            index=models.Index(fields=['level', 'is_published'], name='grammar_top_level_1432be_idx'),
        ),
    ]
