# Generated by Django 5.0.3 on 2026-03-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammarexample',
            name='sentence',
            field=models.TextField(help_text='Câu ví dụ tiếng Anh'),
        ),
        migrations.AlterField(
            model_name='grammarexample',
            name='translation',
            field=models.TextField(blank=True, help_text='Dịch nghĩa tiếng Việt'),
        ),
        migrations.AlterField(
            model_name='grammarrule',
            name='explanation',
            field=models.TextField(blank=True, help_text='Giải thích chi tiết cách dùng (hỗ trợ Markdown/HTML).'),
        ),
    ]
