# Generated by Django 5.0.3 on 2026-03-28 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_grammar_lesson_type'),
        ('grammar', '0002_alter_grammarexample_sentence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarQuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Điểm phần trăm (0-100)')),
                ('total_questions', models.PositiveIntegerField(default=5)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('attempted_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kết quả Quiz Ngữ pháp',
                'db_table': 'grammar_quiz_result',
            },
        ),
        migrations.AddField(
            model_name='grammartopic',
            name='chapter',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Tên chương (VD: 'Thì cơ bản', 'Modal Verbs'). Dùng để nhóm các topic trên UI.", max_length=200),
        ),
        migrations.AddIndex(
            model_name='grammartopic',
            index=models.Index(fields=['level', 'chapter', 'order'], name='grammar_top_level_dd8e24_idx'),
        ),
        migrations.AddField(
            model_name='grammarquizresult',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to='grammar.grammartopic'),
        ),
        migrations.AddField(
            model_name='grammarquizresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_quiz_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='grammarquizresult',
            unique_together={('user', 'topic')},
        ),
    ]
