# Generated by Django 5.0.3 on 2026-03-31 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0003_grammarquizresult_grammartopic_chapter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên chương (VD: Present tenses)', max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('level', models.CharField(choices=[('A1', 'A1 — Beginner'), ('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper Intermediate'), ('C1', 'C1 — Advanced'), ('C2', 'C2 — Proficiency')], db_index=True, default='A1', max_length=2)),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='📚', max_length=50)),
            ],
            options={
                'verbose_name': 'Chương Ngữ pháp',
                'verbose_name_plural': 'Danh sách Chương Ngữ pháp',
                'db_table': 'grammar_chapter',
                'ordering': ['level', 'order'],
            },
        ),
        migrations.RemoveIndex(
            model_name='grammartopic',
            name='grammar_top_level_dd8e24_idx',
        ),
        migrations.AddIndex(
            model_name='grammarchapter',
            index=models.Index(fields=['level', 'order'], name='grammar_cha_level_ecdfa0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grammarchapter',
            unique_together={('level', 'slug')},
        ),
        # Drop NOT NULL and clear stale empty-string values before altering to FK
        migrations.RunSQL(
            sql="ALTER TABLE grammar_topic ALTER COLUMN chapter DROP NOT NULL; UPDATE grammar_topic SET chapter = NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='grammartopic',
            name='chapter',
            field=models.ForeignKey(blank=True, help_text='Chương phân loại chủ đề (VD: Present tenses).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='grammar.grammarchapter'),
        ),
    ]
