# Generated by Django 5.0.3 on 2026-04-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0004_add_grammar_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarexample',
            name='is_correct',
            field=models.BooleanField(default=True, help_text='True = câu đúng (✓), False = câu sai (✗) dùng để minh họa lỗi.'),
        ),
        migrations.AddField(
            model_name='grammarrule',
            name='grammar_table',
            field=models.JSONField(blank=True, default=dict, help_text='Bảng chia động từ/so sánh dạng responsive. {headers: [...], rows: [[...]]}', verbose_name='Bảng ngữ pháp'),
        ),
        migrations.AddField(
            model_name='grammartopic',
            name='common_mistakes',
            field=models.JSONField(blank=True, default=list, help_text='Danh sách lỗi thường gặp. Mỗi item: {wrong, correct, explanation}.', verbose_name='Lỗi thường gặp'),
        ),
        migrations.AddField(
            model_name='grammartopic',
            name='notes',
            field=models.JSONField(blank=True, default=list, help_text="Danh sách ghi chú/tips bổ sung cho chủ đề. Mỗi item: {text, type} với type: 'tip'|'warning'|'info'.", verbose_name='Ghi chú bổ sung'),
        ),
        migrations.AddField(
            model_name='grammartopic',
            name='signal_words',
            field=models.JSONField(blank=True, default=list, help_text="Danh sách từ/cụm từ dấu hiệu nhận biết (VD: ['now', 'at the moment', 'these days']).", verbose_name='Dấu hiệu nhận biết'),
        ),
    ]
