# Generated by Django 5.0.3 on 2026-04-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0005_add_extended_grammar_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammartopic',
            name='comparison_with',
            field=models.JSONField(blank=True, default=list, help_text='So sánh với thì/cấu trúc dễ nhầm lẫn: {title, difference, examples}.', verbose_name='Phân biệt'),
        ),
        migrations.AddField(
            model_name='grammartopic',
            name='concept_image_url',
            field=models.URLField(blank=True, help_text='Link ảnh minh họa cho khái niệm ẩn dụ (Concept Art).', null=True, verbose_name='Ảnh minh họa khái niệm'),
        ),
        migrations.AddField(
            model_name='grammartopic',
            name='metaphor_title',
            field=models.CharField(blank=True, help_text='VD: Chiếc cầu nối giữa Quá khứ và Hiện tại', max_length=200, verbose_name='Tiêu đề ẩn dụ'),
        ),
        migrations.AddField(
            model_name='grammartopic',
            name='narrative_intro',
            field=models.TextField(blank=True, help_text="Lời mở đầu dẫn dắt, giải thích 'Tại sao' thì này tồn tại.", verbose_name='Lời dẫn dắt'),
        ),
        migrations.AddField(
            model_name='grammartopic',
            name='quick_vibe',
            field=models.CharField(blank=True, help_text="Câu chốt 'thần chú' để nhớ thì (VD: Không cần biết khi nào, chỉ cần biết đã xong).", max_length=255, verbose_name='Thần chú'),
        ),
    ]
