# Generated by Django 5.0.3 on 2026-05-03 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0006_grammartopic_comparison_with_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(default=0, help_text='Điểm % (0-100)')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='grammar.grammartopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lần làm Quiz Ngữ pháp',
                'db_table': 'grammar_quiz_attempt',
            },
        ),
        migrations.CreateModel(
            name='GrammarQuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_source_id', models.PositiveIntegerField(help_text='ID của GrammarExample hoặc Question')),
                ('selected_option', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='grammar.grammarrule')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='grammar.grammarquizattempt')),
            ],
            options={
                'verbose_name': 'Đáp án Quiz Ngữ pháp',
                'db_table': 'grammar_quiz_answer',
            },
        ),
        migrations.CreateModel(
            name='GrammarReviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_review', models.DateField(db_index=True, help_text='Ngày cần ôn tiếp theo')),
                ('interval_days', models.PositiveIntegerField(default=1)),
                ('ease_factor', models.FloatField(default=2.5, help_text='Hệ số dễ (SM-2)')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_schedules', to='grammar.grammarrule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lịch ôn Ngữ pháp (SRS)',
                'db_table': 'grammar_review_schedule',
            },
        ),
        migrations.CreateModel(
            name='ErrorPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(default='general', help_text='VD: chia_động_từ, sai_giới_từ, nhầm_thì', max_length=50)),
                ('count', models.PositiveIntegerField(default=1)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_patterns', to='grammar.grammarrule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_errors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mẫu lỗi Ngữ pháp',
                'db_table': 'grammar_error_pattern',
                'unique_together': {('user', 'rule', 'error_type')},
            },
        ),
        migrations.AddIndex(
            model_name='grammarquizattempt',
            index=models.Index(fields=['user', 'topic', '-started_at'], name='grammar_qui_user_id_0f8545_idx'),
        ),
        migrations.AddIndex(
            model_name='grammarquizanswer',
            index=models.Index(fields=['attempt', 'rule', 'is_correct'], name='grammar_qui_attempt_d501e4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grammarreviewschedule',
            unique_together={('user', 'rule')},
        ),
    ]
