# Generated by Django 5.0.3 on 2026-05-06 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0007_grammarquizattempt_grammarquizanswer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('gap-fill', 'Gap Fill'), ('mc', 'Multiple Choice'), ('error', 'Error Correction')], max_length=20)),
                ('prompt', models.TextField()),
                ('options', models.JSONField(help_text='Danh sách đáp án (list of strings)')),
                ('correct_index', models.PositiveIntegerField()),
                ('explanation', models.TextField(blank=True)),
                ('is_auto_generated', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='Đã được admin kiểm định chất lượng')),
                ('needs_review', models.BooleanField(db_index=True, default=True, help_text='Cần admin duyệt lại (nhiễu vô nghĩa, sai ngữ cảnh)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grammar.grammarrule')),
                ('source_example', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grammar.grammarexample')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='grammar.grammartopic')),
            ],
            options={
                'verbose_name': 'Câu hỏi Quiz Ngữ pháp',
                'verbose_name_plural': 'Quản lý Câu hỏi Quiz',
                'db_table': 'grammar_quiz_question',
                'indexes': [models.Index(fields=['topic', 'is_verified', 'needs_review'], name='grammar_qui_topic_i_e79900_idx')],
                'unique_together': {('topic', 'source_example', 'type')},
            },
        ),
    ]
