# Generated by Django 5.0.3 on 2026-05-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0008_grammarquizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarexample',
            name='difficulty',
            field=models.PositiveIntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], db_index=True, default=2, help_text='Độ khó câu ví dụ (1=Dễ, 2=Trung bình, 3=Khó). Auto-generate heuristic, admin override được.'),
        ),
        migrations.AddField(
            model_name='grammarquizquestion',
            name='difficulty',
            field=models.PositiveIntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], db_index=True, default=2, help_text='Độ khó câu hỏi. Kế thừa từ source_example hoặc admin chỉnh.'),
        ),
    ]
