# Generated by Django 5.0.3 on 2026-03-24 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_vi', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('streak', 'Streak'), ('skill', 'Kỹ năng'), ('speed', 'Tốc độ'), ('milestone', 'Milestone'), ('social', 'Social')], db_index=True, max_length=20)),
                ('condition_type', models.CharField(choices=[('streak_days', 'Streak liên tiếp X ngày'), ('skill_score_gte', 'Điểm kỹ năng ≥ X'), ('chapter_in_hours', 'Hoàn thành chương trong X giờ'), ('night_sessions', 'Học sau 22:00 VN X ngày'), ('words_learned', 'Học được X từ mới'), ('lessons_done', 'Hoàn thành X bài học'), ('perfect_score', 'Đạt 100 điểm lần đầu'), ('top_leaderboard', 'Vào Top X bảng xếp hạng'), ('custom', 'Điều kiện tùy chỉnh')], max_length=30)),
                ('threshold_value', models.IntegerField(default=1)),
                ('icon_url', models.CharField(blank=True, max_length=500, null=True)),
                ('icon_emoji', models.CharField(blank=True, max_length=10, null=True)),
                ('xp_reward', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gamification_achievement',
                'ordering': ['category', 'xp_reward'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('weekly', 'Tuần'), ('monthly', 'Tháng'), ('all_time', 'Toàn thời gian')], db_index=True, max_length=10)),
                ('period_start', models.DateField(db_index=True)),
                ('rank', models.IntegerField()),
                ('xp_total', models.IntegerField(default=0)),
                ('snapshot_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gamification_leaderboardsnapshot',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'gamification_userachievement',
            },
        ),
        migrations.CreateModel(
            name='XPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('exercise_complete', '+10 XP — Hoàn thành bài tập'), ('perfect_score', '+25 XP — Điểm tuyệt đối 100'), ('streak_7', '+50 XP — Streak 7 ngày'), ('chapter_complete', '+100 XP — Hoàn thành chương'), ('daily_challenge', '+20 XP — Daily Challenge'), ('badge_earned', 'XP từ huy hiệu'), ('admin_grant', 'Admin cấp thủ công')], db_index=True, max_length=30)),
                ('xp_amount', models.IntegerField()),
                ('reference_id', models.BigIntegerField(blank=True, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=30, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'gamification_xplog',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_s3_key', models.CharField(blank=True, max_length=500, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.course')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.cefrlevel')),
            ],
            options={
                'db_table': 'gamification_certificate',
            },
        ),
    ]
