# Generated by Django 5.0.3 on 2026-03-24 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaderboardsnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.achievement'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='xplog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='leaderboardsnapshot',
            index=models.Index(fields=['period', 'period_start', 'rank'], name='gamificatio_period_0d91e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaderboardsnapshot',
            constraint=models.UniqueConstraint(fields=('user', 'period', 'period_start'), name='unique_user_period_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='userachievement',
            constraint=models.UniqueConstraint(fields=('user', 'achievement'), name='unique_user_achievement'),
        ),
        migrations.AddIndex(
            model_name='xplog',
            index=models.Index(fields=['user', 'created_at'], name='gamificatio_user_id_bd374d_idx'),
        ),
        migrations.AddIndex(
            model_name='xplog',
            index=models.Index(fields=['source'], name='gamificatio_source_a730e2_idx'),
        ),
    ]
