# Generated by Django 5.0.3 on 2026-03-24 03:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('discount_type', models.CharField(choices=[('percent', '% giảm giá'), ('fixed_vnd', 'Giảm số tiền cố định VNĐ')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_uses', models.IntegerField(blank=True, help_text='Null = không giới hạn', null=True)),
                ('used_count', models.IntegerField(default=0)),
                ('valid_from', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('min_purchase_vnd', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payments_coupon',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('vnpay', 'VNPay'), ('stripe', 'Stripe'), ('manual', 'Thủ công')], max_length=10)),
                ('amount_vnd', models.DecimalField(decimal_places=0, max_digits=12)),
                ('original_amount_vnd', models.DecimalField(decimal_places=0, help_text='Trước giảm giá', max_digits=12)),
                ('discount_vnd', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('success', 'Thành công'), ('failed', 'Thất bại'), ('cancelled', 'Đã huỷ'), ('refunded', 'Đã hoàn tiền')], db_index=True, default='pending', max_length=10)),
                ('gateway_txn_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('gateway_response_json', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('webhook_received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payments_paymenttransaction',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('name_vi', models.CharField(max_length=50)),
                ('billing_period', models.CharField(choices=[('free', 'Demo miễn phí'), ('monthly', 'Hàng tháng'), ('yearly', 'Hàng năm'), ('lifetime', 'Vĩnh viễn')], max_length=10)),
                ('price_vnd', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('original_price_vnd', models.DecimalField(decimal_places=0, default=0, help_text='Giá gốc (để hiện discount)', max_digits=12)),
                ('features_json', models.JSONField(default=list, help_text='Danh sách tính năng dạng list[str]')),
                ('max_lessons_per_day', models.IntegerField(blank=True, help_text='Null = không giới hạn', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payments_subscriptionplan',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Dùng thử'), ('active', 'Đang hoạt động'), ('expired', 'Hết hạn'), ('cancelled', 'Đã huỷ'), ('paused', 'Tạm dừng')], db_index=True, default='trial', max_length=10)),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payments_usersubscription',
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_applied_vnd', models.DecimalField(decimal_places=0, max_digits=12)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='payments.coupon')),
            ],
            options={
                'db_table': 'payments_couponredemption',
            },
        ),
    ]
