# Generated by Django 5.0.3 on 2026-03-28 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicSupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('issue_type', models.CharField(choices=[('account_access', 'Không đăng nhập được / quên thông tin tài khoản'), ('payment', 'Thanh toán / hoàn tiền'), ('technical', 'Lỗi kỹ thuật'), ('learning', 'Vấn đề học tập / nội dung'), ('other', 'Khác')], db_index=True, max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'Mới'), ('auto_converted', 'Đã tự chuyển ticket'), ('triaged', 'Đã xử lý phân luồng'), ('closed', 'Đã đóng'), ('spam_rejected', 'Bị từ chối (spam)')], db_index=True, default='new', max_length=20)),
                ('source', models.CharField(default='public_form', max_length=20)),
                ('is_authenticated_submission', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_source_requests', to='support.supportticket')),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_support_requests', to=settings.AUTH_USER_MODEL)),
                ('triaged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triaged_public_support_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_public_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='support_pub_status_3e7c87_idx'), models.Index(fields=['issue_type', 'created_at'], name='support_pub_issue_t_516006_idx')],
            },
        ),
    ]
