# Generated by Django 5.0.3 on 2026-03-26 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinimalPairSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('focus_phoneme_1', models.CharField(max_length=10)),
                ('focus_phoneme_2', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], db_index=True, default='A1', max_length=2)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Minimal Pair Set',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PhonemeLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], db_index=True, default='A1', max_length=2)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Phoneme Lesson',
                'ordering': ['stage', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PronunciationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('monophthongs', 'Stage 1: Monophthongs'), ('consonants', 'Stage 2: Consonants'), ('diphthongs', 'Stage 3: Diphthongs'), ('advanced', 'Stage 4: Advanced (Connected Speech)')], db_index=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('icon', models.CharField(default='🔤', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pronunciation Stage',
                'verbose_name_plural': 'Pronunciation Stages',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MinimalPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=60)),
                ('ipa', models.CharField(max_length=30)),
                ('audio_url', models.URLField(blank=True, max_length=500)),
                ('audio_s3_key', models.CharField(blank=True, max_length=500)),
                ('meaning', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('pair_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='pronunciation.minimalpairset')),
            ],
            options={
                'verbose_name': 'Minimal Pair',
                'ordering': ['pair_set', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Phoneme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, help_text='IPA symbol e.g. /æ/', max_length=10, unique=True)),
                ('phoneme_type', models.CharField(choices=[('vowel', 'Vowel'), ('consonant', 'Consonant'), ('diphthong', 'Diphthong')], default='vowel', max_length=15)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('audio_url', models.URLField(blank=True, max_length=500)),
                ('audio_s3_key', models.CharField(blank=True, max_length=500)),
                ('mouth_diagram_url', models.URLField(blank=True, max_length=500)),
                ('example_words', models.JSONField(default=list, help_text='[{"word": "cat", "ipa": "/kæt/", "meaning": "con mèo"}]')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phonemes', to='pronunciation.phonemelesson')),
            ],
            options={
                'verbose_name': 'Phoneme',
                'ordering': ['phoneme_type', 'order'],
            },
        ),
        migrations.AddField(
            model_name='phonemelesson',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='pronunciation.pronunciationstage'),
        ),
        migrations.CreateModel(
            name='UserPhonemeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0.0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='pronunciation.phonemelesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phoneme_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Phoneme Progress',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
