# Generated by Django 5.0.3 on 2026-03-26 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronunciation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('explanation', 'Giải thích'), ('tip', 'Mẹo phát âm'), ('examples', 'Ví dụ'), ('common_mistakes', 'Lỗi thường gặp'), ('practice', 'Luyện tập'), ('quiz', 'Kiểm tra')], default='explanation', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, help_text='Main text content for this section')),
                ('items', models.JSONField(default=list, help_text='Structured items: examples, quiz questions, practice phrases, etc.')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pronunciation.phonemelesson')),
            ],
            options={
                'verbose_name': 'Lesson Section',
                'ordering': ['lesson', 'order'],
            },
        ),
    ]
